### PR TITLE
ARM provided SMP work

### PR DESCRIPTION
**Pull request by razvanvirtan**
This draft contains the work made by Justin He from ARM on the Unikraft SMP implementation.
I've created the draft in a fork repository because it needs some changes brought by the virtio PR, that wasn't yet merged into the unikraft main repo.

### CODE REVIEW

File: include/uk/plat/smp.h [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+ * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+ * POSSIBILITY OF SUCH DAMAGE.
+ *
+ */
+#ifndef __PLAT_CMN_SMP_H__
+#define __PLAT_CMN_SMP_H__
+
+#define	MAXCPU		8 /* hard limitation for CPU number */
+extern int cpu_possible_map[MAXCPU];
```
Comment (rene) [inline include/uk/plat/smp.h:42]: Values from this vector are later used to start the CPU with start_cpu(), so it should be uint64_t.

File: plat/kvm/arm/setup.c [hunk 2]
```diff
@@ -238,6 +425,17 @@ void _libkvmplat_start(void *dtb_pointer)
 	uk_pr_info("      stack top: %p\n",
 		   (void *) _libkvmplat_cfg.bstack.start);
 
+	_init_dtb_cpu();
+
+	if (cpu0 < 0) {
+		uint64_t mpidr_reg = SYSREG_READ32(mpidr_el1);
```
Comment (rene) [inline plat/kvm/arm/setup.c:456]: Would be better to have a function to read MIPDR_EL1 register and return only the affinity bits (i.e. with the mask in the if below already applied)....

File: plat/kvm/arm/entry64.S [hunk 3]
```diff
@@ -149,3 +149,33 @@ ENTRY(_libkvmplat_newstack)
...
+	mov x7, #1
+	bl	start_mmu
+
+	/* Jump to the virtual address space */
+	ldr	x15, =mp_virtdone
+	br	x15
+
+mp_virtdone:
+	ldr	x4, =secondary_stacks
+	mov	x5, #(4096 * 4)//TODO
```
Comment (rene) [inline plat/kvm/arm/entry64.S:176]: Stack size is hard coded.

File: plat/kvm/arm/setup.c [hunk 4]
```diff
@@ -28,6 +28,28 @@
...
+#include <ofw/fdt.h>
+
+#ifdef CONFIG_SMP
+#include <uk/plat/smp.h>
+int aps_ready;
+int smp_started;
+int mp_ncpus;
+int smp_cpus = 1;	/* how many cpu's running */
+void mpentry(unsigned long cpu);
+uint8_t secondary_stacks[MAXCPU - 1][__PAGE_SIZE * 4];
```
Comment (rene) [inline plat/kvm/arm/setup.c:48]: Wouldn't be better to have all stacks reserved in linker script as it is for boot core?

Comment (rene) [inline plat/kvm/arm/setup.c:48]: A define for stack size should be used here and in plat/kvm/arm/entry64.S

File: include/uk/plat/smp.h [hunk 5]
```diff
@@ -33,8 +33,15 @@
...
 
+#include <inttypes.h>
+struct pcpu {
+	uint32_t	pc_cpuid;	/* This cpu number */
+};
+
 #define	MAXCPU		8 /* hard limitation for CPU number */
 extern int cpu_possible_map[MAXCPU];
+struct pcpu __pcpu[MAXCPU];
+struct pcpu *pcpup = &__pcpu[0];
```
Comment (rene) [inline include/uk/plat/smp.h:44]: Do we need these two vectors: cpu_possible_map[] and pcpu? I think the logic could be implemented only using the cpu IDs vector.....

File: plat/kvm/arm/setup.c [hunk 6]
```diff
@@ -212,6 +234,171 @@ static void _libkvmplat_entry2(void *arg __attribute__((unused)))
...
+{
+	int fdt_cpu;
+	int naddr, nsizei, cell;
+	const fdt32_t *prop;
+	uint64_t core_id, index;
+	int subnode;
+	int i;
+
+	/* Init the cpu_possible_map */
+	for (i = 0; i < MAXCPU; i++)
```
Comment (rene) [inline plat/kvm/arm/setup.c:247]: MAXCPU is only defined when CONFIG_SMP is enabled. Build will fail if CONFIG_SMP is disabled.

File: plat/kvm/arm/setup.c [hunk 7]
```diff
@@ -378,6 +378,23 @@ void init_secondary(uint64_t cpu)
...
+	a = ukplat_memallocator_get();
+	if (a == NULL)
+		UK_CRASH("memallocator is not initialized\n");
+
+	s = uk_sched_default_init(a);
+	if (unlikely(!s))
+		UK_CRASH("Could not initialize the scheduler in APs\n");
+
+	/* Enable interrupts before starting the application */
+	ukplat_lcpu_enable_irq();
```
Comment (rene) [inline plat/kvm/arm/setup.c:391]: I don't see where GIC CPU Interface was initialized for secondary cores..... actually GIC driver needs to be SMP aware, because it should initialize the distributor only once (from boot core), and then initialize CPU Interface for each core....

File: lib/ukboot/Config.uk [hunk 8]
```diff
@@ -117,4 +117,9 @@ if LIBUKBOOT
 		bool "None"
 
 	endchoice
+
+	config SMP
```
Comment (rene) [inline lib/ukboot/Config.uk:121]: UKPLAT_LCPU_MULTICORE also needs to be selected (or defined) with SMP option...

**Comment by rene** [comment]
@razvanvirtan is this current version working? I've tried to build app-helloworld and is crashing on qemu:
```
[    0.000000] CRIT: [libkvmplat] <traps.c @   67> Unikraft: EL1 sync trap caught
[    0.000000] CRIT: [libkvmplat] <traps.c @   39> Unikraft: Dump registers:
[    0.000000] CRIT: [libkvmplat] <traps.c @   40> 	 SP       : 0x0000000040152a40
[    0.000000] CRIT: [libkvmplat] <traps.c @   41> 	 ESR_EL1  : 0x0000000096000006
[    0.000000] CRIT: [libkvmplat] <traps.c @   42> 	 ELR_EL1  : 0x000000004010afdc
[    0.000000] CRIT: [libkvmplat] <traps.c @   43> 	 LR (x30) : 0x0000000040109a88
[    0.000000] CRIT: [libkvmplat] <traps.c @   44> 	 PSTATE   : 0x00000000200003c5
[    0.000000] CRIT: [libkvmplat] <traps.c @   45> 	 FAR_EL1  : 0x000000000000000c
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x00 ~ x03: 0x000000000000000c 0x000000000000000c 0x000000000000000c 0x800000000000000b
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x04 ~ x07: 0x0000000040152f68 0x0000000000000000 0x0000000040109a2c 0x0000000040109564
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x08 ~ x11: 0x0000000000000000 0x0000000000000073 0x00000000ffffffe8 0x0000000000000000
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x12 ~ x15: 0x00000000ffffffe8 0x0000000040152cd0 0x0000000040119420 0x0000000040119448
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x16 ~ x19: 0x0000000040152f80 0x00000000ffffffe8 0x0000000000000030 0x0000000040152d0a
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x20 ~ x23: 0x000000004011a164 0x0000000000000000 0x0000000040152c18 0x0000000000000020
[    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x24 ~ x27: 0x0000000000000000 0x0000000000000000 0x0000000040119370 0x0000000040152f80
[    0.000000] CRIT: [libkvmplat] <traps.c @   53> 	 x28 ~ x29: 0x000000000000001a 0x0000000040152b60
```
Edited:
Reason: https://github.com/razvanvirtan/unikraft/pull/1#discussion_r701857367

File: include/uk/plat/smp.h [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+ * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+ * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+ * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+ * POSSIBILITY OF SUCH DAMAGE.
+ *
+ */
+#ifndef __PLAT_CMN_SMP_H__
+#define __PLAT_CMN_SMP_H__
+
+#define	MAXCPU		8 /* hard limitation for CPU number */
```
Comment (rene) [inline include/uk/plat/smp.h:41]: This could be configured through KConfig....

File: plat/kvm/arm/setup.c [hunk 10]
```diff
@@ -212,6 +234,171 @@ static void _libkvmplat_entry2(void *arg __attribute__((unused)))
...
+	fdt_for_each_subnode(subnode, _libkvmplat_cfg.dtb, fdt_cpu) {
+		const struct fdt_property *prop;
+		int prop_len = 0;
+
+		index++;
+
+		prop = fdt_get_property(_libkvmplat_cfg.dtb, subnode,
+						"enable-method", NULL);
+		if (!prop || strcmp(prop->data, "psci")) {
+			uk_pr_err("Only support psci method!(%s)\n",
```
Comment (rene) [inline plat/kvm/arm/setup.c:275]: if prop == NULL uk_pr_err() will crash because of prop->data.

File: plat/kvm/arm/setup.c [hunk 11]
```diff
@@ -40,6 +40,13 @@ smcc_psci_callfn_t smcc_psci_call;
 extern void _libkvmplat_newstack(uint64_t stack_start,
 			void (*tramp)(void *), void *arg);
 
+int psci_cpu_on(unsigned long cpu, unsigned long entry)
+{
+	/* PSCI v0.1 and v0.2 both support cpu_on. the parameter @cpu after
+	 * @entry will be passed as x0 for entry */
+	return smcc_psci_hvc_call(PSCI_FNID_CPU_ON, cpu, entry, cpu);
```
Comment (rene) [inline plat/kvm/arm/setup.c:69]: Should be smcc_psci_call() so the corresponding method configured in device tree will be used.

File: plat/kvm/arm/setup.c [hunk 12]
```diff
@@ -212,6 +234,171 @@ static void _libkvmplat_entry2(void *arg __attribute__((unused)))
...
+	smp_cpus += 1;
+
+	if (smp_cpus == mp_ncpus)
+		smp_started = 1;
+}
+
+void start_cpu(uint64_t target_cpu)
+{
+
+	uint32_t pa;
```
Comment (rene) [inline plat/kvm/arm/setup.c:403]: should be __phys_addr (uint64_t), not uint32_t.....

**Comment by michpappas** [comment]
Hi @razvanvirtan, looks like this series does not implement the new SMP APIs introduced in https://github.com/unikraft/unikraft/pull/244. Moreover there are parts that would probably deserve their own PR (eg PSCI), and other parts that exceed the scope, such as initializing the scheduler. I think this needs to be reworked.

**Comment by razvanvirtan** [comment]
> @razvanvirtan is this current version working? I've tried to build app-helloworld and is crashing on qemu:
> 
> ```
> [    0.000000] CRIT: [libkvmplat] <traps.c @   67> Unikraft: EL1 sync trap caught
> [    0.000000] CRIT: [libkvmplat] <traps.c @   39> Unikraft: Dump registers:
> [    0.000000] CRIT: [libkvmplat] <traps.c @   40> 	 SP       : 0x0000000040152a40
> [    0.000000] CRIT: [libkvmplat] <traps.c @   41> 	 ESR_EL1  : 0x0000000096000006
> [    0.000000] CRIT: [libkvmplat] <traps.c @   42> 	 ELR_EL1  : 0x000000004010afdc
> [    0.000000] CRIT: [libkvmplat] <traps.c @   43> 	 LR (x30) : 0x0000000040109a88
> [    0.000000] CRIT: [libkvmplat] <traps.c @   44> 	 PSTATE   : 0x00000000200003c5
> [    0.000000] CRIT: [libkvmplat] <traps.c @   45> 	 FAR_EL1  : 0x000000000000000c
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x00 ~ x03: 0x000000000000000c 0x000000000000000c 0x000000000000000c 0x800000000000000b
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x04 ~ x07: 0x0000000040152f68 0x0000000000000000 0x0000000040109a2c 0x0000000040109564
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x08 ~ x11: 0x0000000000000000 0x0000000000000073 0x00000000ffffffe8 0x0000000000000000
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x12 ~ x15: 0x00000000ffffffe8 0x0000000040152cd0 0x0000000040119420 0x0000000040119448
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x16 ~ x19: 0x0000000040152f80 0x00000000ffffffe8 0x0000000000000030 0x0000000040152d0a
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x20 ~ x23: 0x000000004011a164 0x0000000000000000 0x0000000040152c18 0x0000000000000020
> [    0.000000] CRIT: [libkvmplat] <traps.c @   50> 	 x24 ~ x27: 0x0000000000000000 0x0000000000000000 0x0000000040119370 0x0000000040152f80
> [    0.000000] CRIT: [libkvmplat] <traps.c @   53> 	 x28 ~ x29: 0x000000000000001a 0x0000000040152b60
> ```
> 
> Edited:
> Reason: [#1 (comment)](https://github.com/razvanvirtan/unikraft/pull/1#discussion_r701857367)

It works on my local, but I have to specify the number of cores in the qemu command. This is what I use for running:
`qemu-system-aarch64 -machine virt -cpu cortex-a57 -kernel build/app-helloworld_kvm-arm64.dbg -nographic -smp 3`

**Comment by razvanvirtan** [comment]
> Hi @razvanvirtan, looks like this series does not implement the new SMP APIs introduced in [unikraft#244](https://github.com/unikraft/unikraft/pull/244). Moreover there are parts that would probably deserve their own PR (eg PSCI), and other parts that exceed the scope, such as initializing the scheduler. I think this needs to be reworked.

@michpappas @rene Yes, I am currently working on making this compliant with the new API, will come with specific PRs asap. I will also integrate there Rene's comments. Thank you for your feedback!

File: plat/kvm/arm/setup.c (hunk 2 above)
Comment (razvanvirtan) [reply plat/kvm/arm/setup.c:456]: @rene Would it also be useful to initialize cpu0 with bits [11:8] (cpuid) of mpidr? And define a function that extracts this bits for the current cpu, similar to [ukplat_lcpu_id](https://github.com/unikraft/unikraft/pull/244/files#diff-b3e085db7a20bf49db808a720de7cbaed4bf5bcc7bcbed4d472562d9cd791759R129) from the x86 implementation.
I'm thinking that this would keep a difference between physical and logical ids.

Comment (rene) [reply plat/kvm/arm/setup.c:456]: @razvanvirtan , yes, I think IDs of all cores must be initialized. IMO the function to get the ID should return only the affinity fields grouped together, in case of Cortex-A we have the following format for MIPDR_EL1:
image
So the function should return in a single value Aff? grouped into a single value, like this: |Aff3|Aff2|Aff1|Aff0|

Comment (razvanvirtan) [reply plat/kvm/arm/setup.c:456]: @rene I think the physical ids are already initialized for all cores in `_init_dtb_cpu()` (they are read from the device tree and stored in the `cpus[]` vector), so we don't need to use `ukplat_lcpu_id()` for that.
However, `ukplat_lcpu_id()` will provide a way to find the id of the core it is running on. This can't be done by using the cpus vector, since we don't know the index (logical id) of the current cpu. Therefore, finding the boot core physical id will be only one usecase for this function.
